### ISSUE TITLE
Constant Function returns only one number

### ISSUE THREAD

**Issue by hayalaso** [threeML/astromodels#109]
The constant function just returns one number, even if you have an array of energies. 

Possible solution:
```
def evaluate(self, x, k):
        return k*np.ones(np.size(x))
```

**Comment by grburgess** [comment]
hmm. @giacomov is this not the intended result?

**Comment by giacomov** [comment]
Nope.  A constant function should return that constant no matter what energy is asked for. But if x is a vector of 100 energies, you should get back a vector of size 100 all with the same value (the constant).

```f(1.0) -> c``` but also ```f([1.0, 2.0, 3.0]) -> [c, c, c]```

**Comment by grburgess** [comment]
@hayalaso can you fix and make a PR?
