### ISSUE TITLE
EBLattenuation: EBL model not retained during copying etc. 

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#114]
https://github.com/threeML/astromodels/blob/e79942f835ee50b8b086bfde2af1dc2e4fd4fbe6/astromodels/functions/functions.py#L1650 

The EBLattenuation class does not retain the user's choice of EBL attenuation model when being copied or saved to file. Instead, after a model containing a source with EBL attenuation is copied or saved to disk and reloaded, it always defaults to the Dominguez attenuation model.

The EBLattenuation class is lacking an `extra_setup` dictionary that could keep track of the model name. However, in trying to solve the issue by adding a `to_dict` function defining such a dictionary, I came across issue https://github.com/threeML/astromodels/issues/113 , which will need to be solved first before moving forward with the EBLattenuation problem (EBLattenuation is typically used as part of a composite function).

Example illustrating the problem:

```
from threeML import *
from copy import deepcopy

E = [0.1, 1.0, 10.]*u.TeV

print "Printing spectra at", E, "with different EBL models"

for name in ['gilmore', 'dominguez', 'franceschini', 'kneiske']: 

  ebl = EBLattenuation()
  spectrum = Powerlaw()*ebl
  source = PointSource("source", 80, 20, spectrum)

  spectrum.redshift_2 = 0.2
  spectrum.K_1 = 1e-15/u.TeV/u.cm**2/u.s 
  spectrum.piv_1 = 1*u.TeV
  spectrum.index_1 = -2
  ebl.set_ebl_model(name)
  
  model = Model( source )
  model2 = deepcopy(model)

  print "%15s" % name, "original:", model.get_total_flux( E ), "deepcopied:", model2.get_total_flux (E)

```

output:

```
Printing spectra at [ 0.1  1.  10. ] TeV with different EBL models
        gilmore original: [9.26726667e-23 9.55909432e-26 4.90191464e-30] deepcopied: [9.52063120e-23 1.00947515e-25 1.50339314e-30]
      dominguez original: [9.52063120e-23 1.00947515e-25 1.50339314e-30] deepcopied: [9.52063120e-23 1.00947515e-25 1.50339314e-30]
   franceschini original: [9.64298553e-23 1.13254712e-25 5.99616695e-31] deepcopied: [9.52063120e-23 1.00947515e-25 1.50339314e-30]
        kneiske original: [9.39981379e-23 1.61169419e-25 1.92099805e-29] deepcopied: [9.52063120e-23 1.00947515e-25 1.50339314e-30]
```

**Comment by grburgess** [comment]
Hi, we have the same problem with the the phabs style models. I'm not sure there is a clever solution without rewriting the model class at a deep level. One could make this a parameter and keep it fixed, but this would really screw up things if it was accidentally freed. 

I think the same would happen in XSPEC with abundances. 

Perhaps it is best to just have a setting int he script?

**Comment by henrikef** [comment]
I think resetting it in the script each time is what Mateo (who originally found this problem) ended up doing. The thing is that for some of us on HAWC, our workflows/example scripts rely a lot on models being copied or saved to file.  E.g. run a bunch of fits (different models, or different detector response files or whatever) on a cluster, save the results to fits, then have a separate script read in these fits files to plot the spectrum or whatever. Or even if you call `calc_TS` for a multi-source model, it works on copies of the original best-fit model. So having to re-set the EBL model each time is prone to errors/mixups. Especially if someone is trying to compare the effect of different EBL models.

I almost think it would be better to just make separate astromodels functions for each supported EBL model, e.g. `EBLattenuation_gilmore`, `EBLattenuation_dominguez` etc. I'll try to get input from some people that actually use the EBL attenuation stuff (I'm 100% galactic 😆).

**Comment by mateofa** [comment]
I agree with Henrike, resetting it in the script wouldn't be practical and prone to mistakes. I remember dealing with the _setup definition, where a default model is required. My first try was to see if I could get things running without the default model being defined, or alternatively plugging in the desired model as a default... no success. 
Actually, it might be a good idea to separate classes according to each model, since most people only use the "traditional" EBL models which are 3-5... is this work-around too grungy?

**Comment by mateofa** [comment]
I'm going to start preparing that work-around, since it's something I can handle. I'll report to this thread as soon as I have a working script.

**Comment by grburgess** [comment]
Thanks! Yeah, the only other solution at the moment would probably need some very low level tinkering. Perhaps we can meet Wednesday on zoom and discuss in more detail?

**Comment by henrikef** [comment]
I forgot, when do you usually have the zoom call? I can try to call in, I've been a bit busy with calls lately 📞

**Comment by grburgess** [comment]
Usually on Wednesday U.S. morning times.

**Comment by mateofa** [comment]
Hello,

I could make it Wednesday morning, what time and platform (zoom, uber_conf)?

Cheers,

Mateo

----------------------------------------------------------------------------------------------------------------------
Mateo Fernández Alonso
Postdoctoral Scholar
Pennsylvania State University
Tel: +1 (814) 996-9015
Mail:  mkf5479@psu.edu
________________________________
