### ISSUE TITLE
pyyaml version pinning leads to conflic with fermipy

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#131]
We require pyyaml version 3.13:

https://github.com/threeML/astromodels/blob/3a02b82732ae45b6d9d2720d13704718c10e530f/setup.cfg#L38

See https://github.com/threeML/astromodels/issues/97 for why things break with newer versions of pyyaml. 

Unfortunately, fermipy requires gammapy, which has required pyyaml >=5.1 for about a year now (and I believe that newer versions of fermipy are incompatible with older gammapy versions). 

So, I believe it's time to try again to get astromodels working with newer versions of pyyaml. Has anyone looked into this at all?

**Comment by ndilalla** [comment]
Hi @henrikef! Yes, I am working on this on the development branch for the new fermitools and root6. Astromodels is ready to work with newer pyyaml while in threeML I am still having some issues with the YAML loader that is deprecated in pyyaml 5.1. So we will need to change a bit our code according to this:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by henrikef** [comment]
Awesome! Let me know if you need any help or would like me to test anything.

**Comment by grburgess** [comment]
I noticed when I tried to modify to the forward version pyyaml that the safe loader was not compatible with our model structure. Is that still the case?

**Comment by henrikef** [comment]
What about the "FullLoader" or "UnsafeLoader" though?

**Comment by grburgess** [comment]
@henrikef I think I tried that.. but I cannot remember. @ndilalla how did you get it to work?

**Comment by henrikef** [comment]
Is there a problem requiring a newer version of pyaml? I vote for no backward compatibility.

**Comment by grburgess** [comment]
I second :)

**Comment by ndilalla** [comment]
No, no problems. We just need to require pyyaml >= 5.1 in the dependency list. I'll go for it.

**Comment by ndilalla** [comment]
I don't why the stupid conda continues to put pyyaml==3.13 as requirement even if I've put pyyaml>=5.1 in the meta and setup files! This is crazy...

**Comment by ndilalla** [comment]
Okay, it should be fixed now.
