### ISSUE TITLE
Problem from astromodels while installing pynchrotron

### ISSUE THREAD

**Issue by asattools** [threeML/astromodels#133]
Hi, 

I have installed fermitools (python 3.7) and threeML successfully. I am trying to installed pynchrotron and a problem which might be due to astromodels (https://github.com/grburgess/pynchrotron/issues/1) is occuring (pytables). Please suggest a solution to this.

Regards and thanks.

**Comment by grburgess** [comment]
It seems pytables is no longer on pip? I'm not even sure if we are using pytables anymore, so I've got a branch building on the CI server to see if that fixes the issue.

**Comment by asattools** [comment]
Yes,
There is installation instruction in pip for pytables https://pypi.org/project/pytable/
and it is there in conda-forge also conda install -c conda-forge pytables

**Comment by ndilalla** [comment]
Thanks @asattools for reporting this issue. We discovered that the conda package `pytables` is simply named `tables` on pip (the package you linked above named `pytable` is a different thing). The fix is ready to be merged and will be shipped with the v2.0.1.

**Comment by asattools** [comment]
> Thanks @asattools for reporting this issue. We discovered that the conda package `pytables` is simply named `tables` on pip (the package you linked above named `pytable` is a different thing). The fix is ready to be merged and will be shipped with the v2.0.1.

Thanks, I shall be waiting for the new version.

**Comment by grburgess** [comment]
@ndilalla thanks!
