### ISSUE TITLE
Powerlaw_flux bug?

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#149]
In powerlaw_flux, it looks like we're multiplying by the flux norm twice. I assume that's unintended, right? (Sorry, should have noticed that during the code review).

https://github.com/threeML/astromodels/blob/ff8c0759739a8ea9781145bc8c817855e6f66a9c/astromodels/functions/powerlaws.py#L184

https://github.com/threeML/astromodels/blob/ff8c0759739a8ea9781145bc8c817855e6f66a9c/astromodels/functions/powerlaws.py#L186

**Comment by grburgess** [comment]
fixed in #150
