### ISSUE TITLE
units in log_normal prior

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#68]
Hi!

I intentionally kept this separate from #67 since  this is less of a problem, just something that could be more user-friendly. 

Currently, the log_normal prior is defined as follows (some spaces removed for brevity):

```
    def evaluate(self, x, F, mu, sigma):
  
      if isinstance(F, astropy_units.Quantity):
            x_ = x.value
        else:
            x_ = x

        norm = self.__norm_const / (sigma * x_)
        return F * norm * np.exp(-np.power(np.log(x_) - mu, 2.) / (2 * np.power(sigma, 2.)))
```

Here, `mu` is forced to be unitless.  If `x` carries units, e.g. a flux norm or a cutoff energy, the user has to keep track of what units will be used internally for that quantity, and then set `mu` accordingly. 

A more straight-forward approach imho would be to define it like this:

```
    def evaluate(self, x, F, M, sigma):
  
        norm = self.__norm_const / (sigma * x_)
        return F * norm * np.exp(-np.power(np.log(x / M), 2.) / (2 * np.power(sigma, 2.)))
```

Where `M` (equivalent to `exp(mu)` ) carries the same units as `x`.

I don't know how many people are using log_normal priors though, so I'm hesitant to change it and potentially break things for everyone else.

**Comment by cbrisboi** [comment]
One way to Combine #67 and this would be to do it this way. We still need to ensure the units are accounted for, which is why I hope checking the units for x/M are dimensionless is correct
`def evaluate(self, x, F, mu, sigma):
        x_=x/M
        if x_.unit != astropy_units.dimensionless_unscaled:
            #error of some sort

        if x_ <=0 or x <=0:
            return 0
        norm = self.__norm_const / (sigma * x)
        return F * norm * np.exp(-np.power(np.log(x_), 2.) / (2 * np.power(sigma, 2.)))`

**Comment by giacomov** [comment]
I actually added a pivot so that all units are preserved. Now `sigma` and `mu` have the same unit as `x`. 

Let me know if this fixes your problem, and if it does please close the issue.

**Comment by henrikef** [comment]
Thanks!

in `from_unit_cube(self, x)`, shouldn't we also have to divide by the pivot? Since `res = mu + sigma * sqrt_two * erfcinv(2 * (1 - x))` can potentially have units now?

**Comment by giacomov** [comment]
`from_unit_cube` is called by Multinest, not by the user, so the call will never have units.

However, as it is now, if for some weird reason the user changes the value of the pivot then the `from_unit_cube` call will use a different distribution than the normal `evaluate` function, so I guess dividing there by `piv` might be a good idea. If you wanna change that, go ahead!
