### ISSUE TITLE
Several Templates at once

### ISSUE THREAD

**Issue by ssteinmassl** [threeML/astromodels#73]
Hi,
I am running into issues while loading several template models at once. when trying to plot them with a looping function for a given parameter set some of them seem to adapt values from other template models before them in the loop. Unfortunately there does not seem to be a regularity when this happens or not. So sometimes even rerunning the same script yields different results. Further if I just print out the values for a given parameter set the values are sometimes coming from different template models as well. Hence I guess that some of the values might be cached somewhere and then reused instead calling the actual template model. I used TemplateModel('name', log_interp = False) and the plotted them as a function of phase between 0 and 1. 

Cheers 
Simon

**Comment by giacomov** [comment]
I am investigating this and I am pretty positive this is related to the memoization function.

While I find a fix, you can use the following workaround:

```python
with use_astromodels_memorization(False):
    [perform the fit]
```
which deactivate temporarily the memoization functionality.

**Comment by grburgess** [comment]
Is this issue solved or still active?

**Comment by giacomov** [comment]
I am pretty sure this has been solved.
