### ISSUE TITLE
reloading of model with recursively linked parameters failed

### ISSUE THREAD

**Issue by ssteinmassl** [threeML/astromodels#82]
Hi,
I have been working with a model, in which I linked two parameters with a StepFunction(). I then linked the StepFunction.lower_ bound to another parameter. Doing BayesianAnalysis.sample(...) it would then fail after the sampling when trying to clone the model. Saving the model and trying to reload it would obviously give a similar error message. Is there any good solution for that?

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-87-1c5fb4a97670> in <module>()
----> 1 test = load_model('my_modelRim.yml')

/home/simonste/.venv/3ml/local/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in load_model(filename)
     35     parser = ModelParser(filename)
     36 
---> 37     return parser.get_model()
     38 
     39 

/home/simonste/.venv/3ml/local/lib/python2.7/site-packages/astromodels/core/model_parser.pyc in get_model(self)
    169         for link in self._links:
    170 
--> 171             path = link['parameter_path']
    172             variable = link['variable']
    173             law = link['law']

/home/simonste/.venv/3ml/local/lib/python2.7/site-packages/astromodels/core/model.pyc in __getitem__(self, path)
    258         """
    259 
--> 260         return self._get_child_from_path(path)
    261 
    262     def __contains__(self, path):

AttributeError: Node StepFunction does not exist`

**Comment by giacomov** [comment]
@ssteinmassl can you attach here the file "my_modelRim.yml"?

**Comment by ssteinmassl** [comment]
[my_modelRim.yml.zip](https://github.com/giacomov/astromodels/files/2252895/my_modelRim.yml.zip)

**Comment by ssteinmassl** [comment]
The setup of my model 
`my_model = Model(PointSdict['ps_g'],PointSdict['ps_r']
                 ,PointSdict['ps_i'],PointSdict['ps_z']
                 ,PointSdict['ps_J'],PointSdict['ps_H'],PointSdict['ps_K'])`
The links where the origin for the reloading/cloning problem is:
`# PENALTY DSIZE FUNCTION



DSlinc = StepFunction()
DSlinc.upper_bound = 1
DSlinc.upper_bound.fix = True
DSlinc.value = 1
DSlinc.value.fix = True

# DscaleMin Function Setup


DSC = Diskminfunc()
DSC.M_star = M2(4200.)
DSC.M_star.fix = True
DSC.P = 2 * 0.1960797
DSC.P.fix =True`

`my_model.link(my_model.Xrb_gband_source.spectrum.main.Xrb_Rim_gband.penalty,
              my_model.Xrb_gband_source.spectrum.main.Xrb_Rim_gband.Dsize,
              DSlinc)

my_model.link(my_model.Xrb_gband_source.spectrum.main.Xrb_Rim_gband.penalty.StepFunction.lower_bound,
              my_model.Xrb_gband_source.spectrum.main.Xrb_Rim_gband.Mass,DSC)`

**Comment by grburgess** [comment]
Is this issue solved or still active?
