### ISSUE TITLE
XSPEC failing

### ISSUE THREAD

**Issue by grburgess** [threeML/astromodels#96]
It seems the newer version of XSPEC has removed some models which are hardcoded into our interface. 

The first that fails is: xsgsmt

This was in an older XSPEC but is now gone. I do not see any exception catching that avoids compiling a model that is not there. I would not want to remove this as older XSPEC will not work. Can someone test that it is not just a problem with my setup?

**Comment by grburgess** [comment]
Ok. I've looked at the sherpa _xspec.cc and seen that they have a newer version which has clauses for different XSPEC versions. If I remember correctly, this is what @giacomov modeled his version on. 

Now, I also remember that we made some changes to deal with strange things (evaluating the model as an integral over energy vs at the energy). Should we just swap this file for the one we have?

**Comment by giacomov** [comment]
You can try to do that, the tests should tell you if that breaks things

**Comment by grburgess** [comment]
Ok. Looking at the new sherpa build. The user is responsible for building the XSPEC models after installing. This allows the specifying of the version number. Yes, this puts a lot more and the user... but I think this is nice idea

**Comment by grburgess** [comment]
Ok. I have it working... mostly. There is an addition requirement in the install of XSPEC where newer version requires us to set an env. variable XSPEC_VERSION=12.10.1 for example. This allows the compile step to implement the proper models. 

We need to put this into the documentation... somewhere.

**Comment by giacomov** [comment]
great!
I think there should be a default value of that variable for the version
that is implemented in the xspec-modelsonly package. That way our conda
customers (which are most of the people) won't need to do anything specific.

**Comment by grburgess** [comment]
I'm currently stuck. The new version segfaults when calling any of the functions and I can't figure out where.
