### ISSUE TITLE
pyyaml 5.1

### ISSUE THREAD

**Issue by henrikef** [threeML/astromodels#97]
Some people have reported issues using the new version of pyyaml (5.1). 

There are warnings like 

```
/Users/Chang/miniconda3/envs/st_test/lib/python2.7/site-packages/astromodels/functions/function.py:120: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  function_definition = my_yaml.load(dct['__doc__'])
```

The code runs, but there are issues with parsing functions/loading models from file, leading to errors like 

```
E                                  UnitsError: Looks like you didn't provide all the units, or you provided the wrong ones, when calling function Powerlaw
```
or
```
E               ModelSyntaxError: Function polarization, specified as shape for main of source one, is not a known function
```
during the tests. 

Again, the underlying issues is changes in pyyaml, which break parsing of yml files in astromodels. See also https://github.com/yaml/pyyaml/issues/265 . I suggest anyone experiencing issues downgrade to pyyaml==3.13 and yaml==0.1.7.

There are some more issues with the new version of pyyaml, see e.g. https://github.com/yaml/pyyaml/issues/275 .

**Comment by henrikef** [comment]
@cdr397

**Comment by grburgess** [comment]
Hi! I've made the changes in the setup and this indeed solved the problem. However, I'm making that change in my branch for fixing the builds and there is still a weird issue with the conda builds for OSX. I'll keep working at it over the weekend.

**Comment by grburgess** [comment]
solved

**Comment by henrikef** [comment]
Was the solution to this just downgrading to pyyaml 3.13? If that's the case, I would think that eventually we'll need to update our code to work with the new yaml loaders. Or has that been done already?
