### ISSUE TITLE
Latitude_galactic_diffuse broken

### ISSUE THREAD

**Issue by cbrisboi** [threeML/astromodels#98]
Problem in Latitude_galactic_diffuse when using hawc_hal, astromodels functions should be plugin agnostic. Still working on a full description @zhoouhaoo suggested it may be related to get_boundaries().

For my analysis, the fit **only** converges when both K(shape) and K(flux norm) is fit for the galactic diffuse. After talking to people, only 1 of these should be fit.

**Comment by henrikef** [comment]
Tracked down why parameters with the same name are a problem for hawc_hal, see https://github.com/threeML/astromodels/pull/99#issuecomment-476450957 (actually should have replied here rather than in the pull request).

**Comment by grburgess** [comment]
Solved by @henrikef  via #100
